services:
  bot:
    build: .
    container_name: cordle_bot
    stop_grace_period: 40s
    depends_on:
      db:
        condition: service_healthy
  db:
    build: deployment/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=pass
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 3
    container_name: cordle_db
    volumes:
      - mysql:/var/lib/mysql
    expose:
      - "3306"
volumes:
  mysql: